# Generated by Django 5.2.10 on 2026-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_user'),
        ),
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background_user'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
