# Generated by Django 5.2.10 on 2026-03-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/user.png', null=True, upload_to='avatar/'),
        ),
    ]
