services:
  db:
    image: postgres:16
    container_name: Database_Web_Chat
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: Redis_Web_Chat
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
