# Generated by Django 5.2.10 on 2026-03-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_repies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='repies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
    ]
