# Generated by Django 5.2.10 on 2026-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aura',
            new_name='like',
        ),
        migrations.AddField(
            model_name='blog',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
