# Generated by Django 5.2.10 on 2026-02-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_aura_comment_like_blog_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='verify_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
