# Generated by Django 5.2.10 on 2026-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_verify_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
