# Generated by Django 5.2.10 on 2026-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='blog_video/'),
        ),
    ]
